"""Change height to Integer

Revision ID: 111ad8d39ffb
Revises: 99449a4f5d9a
Create Date: 2025-05-18 14:45:04.800306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111ad8d39ffb'
down_revision = '99449a4f5d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
