"""empty message

Revision ID: 734b840c87b2
Revises: 
Create Date: 2025-05-02 13:23:10.952939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734b840c87b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('photo', sa.String(length=2083), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('fav_user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('parish', sa.String(length=100), nullable=True),
    sa.Column('biography', sa.String(length=180), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('fav_cuisine', sa.String(length=100), nullable=True),
    sa.Column('fav_colour', sa.String(length=50), nullable=True),
    sa.Column('fav_school_subject', sa.String(length=100), nullable=True),
    sa.Column('political', sa.Boolean(), nullable=True),
    sa.Column('religious', sa.Boolean(), nullable=True),
    sa.Column('family_oriented', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('favourites')
    op.drop_table('users')
    # ### end Alembic commands ###
