"""empty message

Revision ID: 99449a4f5d9a
Revises: e800e09b68f1
Create Date: 2025-05-03 22:23:59.955866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99449a4f5d9a'
down_revision = 'e800e09b68f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_fk', sa.Integer(), nullable=False))
        batch_op.drop_constraint('profiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id_fk'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profiles_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_id_fk')

    # ### end Alembic commands ###
