"""empty message

Revision ID: e800e09b68f1
Revises: 734b840c87b2
Create Date: 2025-05-02 14:24:10.523310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e800e09b68f1'
down_revision = '734b840c87b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_fav', ['user_id_fk', 'fav_user_id_fk'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('parish',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('biography',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('race',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fav_cuisine',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fav_colour',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('fav_school_subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('political',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('religious',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('family_oriented',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint('profiles_user_id_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=2083),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=2083),
               nullable=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint('profiles_user_id_key', ['user_id'])
        batch_op.alter_column('family_oriented',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('religious',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('political',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('fav_school_subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('fav_colour',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('fav_cuisine',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('race',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('biography',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
        batch_op.alter_column('parish',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_fav', type_='unique')

    # ### end Alembic commands ###
